import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generatePayslipPDF = (payroll) => {
    try {
        console.log("Generating PDF for:", payroll);
        if (!payroll) {
            alert("Error: Invalid payroll data");
            return;
        }

        const doc = new jsPDF();
        const companyName = "DayFlow Systems";
        
        // Header
        doc.setFontSize(22);
        doc.setTextColor(40);
        doc.text(companyName, 105, 20, { align: 'center' });
        
        doc.setFontSize(16);
        doc.text("Payslip", 105, 30, { align: 'center' });
        
        // Details
        doc.setFontSize(12);
        doc.setTextColor(0);
        
        const firstName = payroll.user?.firstName || 'Employee';
        const lastName = payroll.user?.lastName || '';
        const fullName = `${firstName} ${lastName}`;
        const empId = payroll.user?.employeeId || 'N/A';
        
        doc.text(`Employee Name: ${fullName}`, 20, 50);
        doc.text(`Employee ID: ${empId}`, 20, 60);
        doc.text(`Month: ${payroll.month || '-'}`, 140, 50);
        doc.text(`Status: ${payroll.status || 'Pending'}`, 140, 60);
        
        // Earnings Table
        const earnings = [
            ["Basic Salary", `$${payroll.basicSalary || 0}`],
            ["Allowances", `$${payroll.allowances || 0}`],
            ["Deductions", `-$${payroll.deductions || 0}`],
        ];
        
        const netSalary = payroll.netSalary || 0;
        
        autoTable(doc, {
            startY: 70,
            head: [["Components", "Amount"]],
            body: earnings,
            theme: 'grid',
            headStyles: { fillColor: [66, 133, 244] },
        });
        
        // Net Salary
        const finalY = doc.lastAutoTable.finalY + 10;
        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.text(`Net Salary: $${netSalary}`, 140, finalY);
        
        // Footer
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.text("Generated by DayFlow HRMS", 105, 280, { align: 'center' });
        
        doc.save(`Payslip_${firstName}_${payroll.month || 'Report'}.pdf`);
    } catch (error) {
        console.error("PDF Generation Error:", error);
        alert("Failed to generate PDF. Please check console for details.");
    }
};
